### ISSUE TITLE
OAS Format for Schemas

### ISSUE THREAD

**Issue by jtpugac** [Amartus/SonataBlendingTool#6]
It would be useful to have schemas in OAS format in order to leverage VSCode plugins such as Markdown generation, PlantUML generation and auto-code generation.

**Comment by bartoszm** [comment]
I have implemented this feature  and added to new release https://github.com/Amartus/SonataBlendingTool/releases/tag/v1.8.0

**Comment by bartoszm** [comment]
@jtpugac I am closing as resolved but if you have any comments please reopen and give me your feedback
