### ISSUE TITLE
Overwire file option

### ISSUE THREAD

**Issue by jtpugac** [Amartus/SonataBlendingTool#7]
Currently, if the Swagger/OpenAPI file exists, there is not an option to overwrite.  The blending tool throws an error.  It would be helpful to either prompt to overwrite or write a new file with new name.

**Comment by bartoszm** [comment]
Hi @jtpugac,
Version 1.7.1 https://github.com/Amartus/SonataBlendingTool/releases/tag/v1.7.1 already has this option for `blend` command
